name: mvvm_clean_arc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.4
  build_runner: ^2.3.3
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  dio: ^5.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1


flutter:

  uses-material-design: true


